import { Flashcard } from "../components/flashcard/models/flashcard.model";

export const javascriptFlashcardsData = [
    new Flashcard("What is JavaScript?", "JavaScript is a high-level, interpreted programming language."),
    new Flashcard("What are the data types in JavaScript?", "The data types in JavaScript are Number, String, Boolean, Object, Null, and Undefined."),
    new Flashcard("What is the difference between null and undefined in JavaScript?", "Null is an assignment value that represents no value or no object, while undefined means a variable has been declared but has not yet been assigned a value."),
    new Flashcard("What is the difference between '==' and '===' operators in JavaScript?", "'==' compares the values of two variables, while '===' compares both the values and the types of the variables."),
    new Flashcard("What is an anonymous function in JavaScript?", "An anonymous function is a function without a name. It is often used as a callback function or as an immediate function."),
    new Flashcard("What is a closure in JavaScript?", "A closure is a function that has access to its own scope, the scope of the outer function, and the global scope."),
    new Flashcard("What is event delegation in JavaScript?", "Event delegation is a technique where you attach a single event listener to a parent element, rather than attaching multiple event listeners to individual child elements."),
    new Flashcard("What is the difference between 'let', 'const', and 'var' in JavaScript?", "'let' and 'const' are block-scoped variables, while 'var' is function-scoped. 'let' allows reassignment, 'const' does not, and 'var' can be reassigned."),
    new Flashcard("What is the purpose of the 'this' keyword in JavaScript?", "The 'this' keyword refers to the object that the function is a method of, or the object that is currently being constructed by a constructor function."),
    new Flashcard("What is the difference between 'null' and 'undefined' in JavaScript?", "'null' is an assignment value that represents no value or no object, while 'undefined' means a variable has been declared but has not yet been assigned a value."),
    new Flashcard("What is the purpose of the 'use strict' directive in JavaScript?", "The 'use strict' directive enables strict mode, which catches common mistakes and enforces stricter rules in JavaScript."),
    new Flashcard("What is the purpose of the 'typeof' operator in JavaScript?", "The 'typeof' operator returns the data type of a value, such as 'number', 'string', 'boolean', 'object', 'function', 'undefined', or 'symbol'."),
    new Flashcard("What is the difference between '==' and '===' operators in JavaScript?", "'==' compares the values of two variables, while '===' compares both the values and the types of the variables."),
    new Flashcard("What is the purpose of the 'new' keyword in JavaScript?", "The 'new' keyword is used to create an instance of an object or to invoke a constructor function."),
    new Flashcard("What is hoisting in JavaScript?", "Hoisting is a JavaScript mechanism where variables and function declarations are moved to the top of their respective scopes during the compilation phase."),
    new Flashcard("What is the purpose of the 'NaN' value in JavaScript?", "'NaN' stands for 'Not-a-Number' and represents an invalid or unrepresentable value in JavaScript."),
    new Flashcard("What is the difference between 'let' and 'var' in JavaScript?", "'let' is block-scoped, while 'var' is function-scoped. 'let' allows redeclaration in the same block, while 'var' does not."),
    new Flashcard("What is the purpose of the 'async' and 'await' keywords in JavaScript?", "The 'async' keyword is used to define an asynchronous function, and the 'await' keyword is used to pause the execution of an asynchronous function until a promise is fulfilled or rejected."),
    new Flashcard("What is the purpose of the 'try-catch' statement in JavaScript?", "The 'try-catch' statement allows you to catch and handle exceptions that occur within a block of code."),
    new Flashcard("What is the difference between 'var', 'let', and 'const' in JavaScript?", "'var' is function-scoped, 'let' and 'const' are block-scoped. 'var' allows redeclaration in the same scope, 'let' allows reassignment, and 'const' does not allow reassignment."),
    new Flashcard("What is the purpose of the 'map' function in JavaScript?", "The 'map' function is used to create a new array by applying a provided function to each element of an existing array."),
    new Flashcard("What is the purpose of the 'filter' function in JavaScript?", "The 'filter' function is used to create a new array with all elements that pass a provided test."),
    new Flashcard("What is the purpose of the 'reduce' function in JavaScript?", "The 'reduce' function is used to reduce an array to a single value by applying a provided function to each element of the array."),
    new Flashcard("What is the purpose of the 'forEach' function in JavaScript?", "The 'forEach' function is used to execute a provided function once for each array element."),
    new Flashcard("What is the purpose of the 'bind' function in JavaScript?", "The 'bind' function is used to create a new function that, when called, has its 'this' keyword set to a specific value."),
    new Flashcard("What is the purpose of the 'call' and 'apply' functions in JavaScript?", "The 'call' and 'apply' functions are used to invoke a function with a specified 'this' value and arguments provided individually or as an array, respectively."),
    new Flashcard("What are arrow functions in JavaScript?", "Arrow functions are a shorthand syntax for writing function expressions. They have a more concise syntax and inherit the 'this' value from the surrounding context."),
    new Flashcard("What is the purpose of the 'Promise' object in JavaScript?", "The 'Promise' object is used for asynchronous computations. It represents a value that may be available now, in the future, or never."),
    new Flashcard("What is the purpose of the 'fetch' function in JavaScript?", "The 'fetch' function is used to make HTTP requests and retrieve resources asynchronously."),
    new Flashcard("What is the purpose of the 'addEventListener' function in JavaScript?", "The 'addEventListener' function is used to attach an event handler to a specified element, allowing it to listen for a specific event."),
    new Flashcard("What is the difference between 'let' and 'const' in JavaScript?", "'let' allows reassignment, while 'const' does not. 'let' is block-scoped, while 'const' is block-scoped and also requires initialization."),
    new Flashcard("What is the purpose of the 'setTimeout' function in JavaScript?", "The 'setTimeout' function is used to execute a specified function or code snippet after a specified delay."),
    new Flashcard("What is the purpose of the 'setInterval' function in JavaScript?", "The 'setInterval' function is used to repeatedly execute a specified function or code snippet at a specified time interval."),
    new Flashcard("What is the difference between '==' and '===' in JavaScript?", "'==' checks for equality after converting the operands to a common type, while '===' checks for equality without type conversion."),
    new Flashcard("What is a closure in JavaScript?", "A closure is a function that has access to its own scope, the scope of the outer function, and the global scope."),
    new Flashcard("What is the difference between 'let', 'const', and 'var' in JavaScript?", "'let' and 'const' are block-scoped variables, while 'var' is function-scoped."),
    new Flashcard("What is event delegation in JavaScript?", "Event delegation is a technique where a single event listener is added to a parent element to handle events for all its child elements."),
    new Flashcard("What is the purpose of the 'this' keyword in JavaScript?", "The 'this' keyword refers to the object that the function is executing in."),
    new Flashcard("What is the difference between 'null' and 'undefined' in JavaScript?", "'null' is an assignment value that represents no value or an empty object, while 'undefined' means a variable has been declared but has not been assigned a value."),
    new Flashcard("What is a callback function in JavaScript?", "A callback function is a function passed as an argument to another function, which is then invoked within the outer function."),
    new Flashcard("What are the different ways to declare a function in JavaScript?", "Functions can be declared using function declarations, function expressions, arrow functions, and methods."),
    new Flashcard("What is the 'this' keyword in JavaScript?", "The 'this' keyword refers to the object that is currently executing the code."),
    new Flashcard("What are the different types of loops in JavaScript?", "JavaScript supports three types of loops: 'for' loop, 'while' loop, and 'do-while' loop."),
    new Flashcard("What is the purpose of the 'typeof' operator in JavaScript?", "The 'typeof' operator is used to determine the type of a variable or expression."),
    new Flashcard("What is a promise in JavaScript?", "A promise is an object representing the eventual completion or failure of an asynchronous operation."),
    new Flashcard("What is the difference between 'null' and 'undefined' in JavaScript?", "'null' represents the intentional absence of any object value, while 'undefined' represents an uninitialized or missing value."),
    new Flashcard("What is the 'event' object in JavaScript?", "The 'event' object contains information about an event that occurred, such as the type of event and the target element."),
    new Flashcard("What is the difference between 'let' and 'var' in JavaScript?", "'let' has block scope and is limited to the block where it is defined, while 'var' has function scope and is accessible throughout the function."),
    new Flashcard("What is the purpose of the 'document' object in JavaScript?", "The 'document' object represents the HTML document and provides methods and properties for manipulating the document."),
    new Flashcard("What is a prototype in JavaScript?", "A prototype is an object that is used as a blueprint for creating other objects. It allows objects to inherit properties and methods from other objects."),
    new Flashcard("What is the difference between '==', '===', and '!=' in JavaScript?", "'==' checks for equality with type coercion, '===' checks for equality without type coercion, and '!=' checks for inequality with type coercion."),
    new Flashcard("What is event bubbling in JavaScript?", "Event bubbling is the process where an event triggered on a child element will also trigger on its parent elements."),
    new Flashcard("What is the 'use strict' mode in JavaScript?", "The 'use strict' mode is a way to enable strict mode in JavaScript, which helps to catch common coding mistakes and enforce stricter rules."),
    new Flashcard("What is the difference between 'call' and 'apply' methods in JavaScript?", "'call' and 'apply' are methods used to invoke a function with a specified 'this' value, but 'apply' accepts an array as the second argument for passing function arguments."),
    new Flashcard("What is the purpose of the 'map' method in JavaScript?", "The 'map' method is used to create a new array by applying a function to each element of an existing array."),
    new Flashcard("What is the difference between 'let' and 'const' in JavaScript?", "'let' allows reassignment of values, while 'const' creates a read-only reference to a value that cannot be reassigned."),
    new Flashcard("What is the purpose of the 'bind' method in JavaScript?", "The 'bind' method is used to create a new function that, when called, has a specified 'this' value and sets the arguments of the original function."),
    new Flashcard("What is the purpose of the 'querySelector' method in JavaScript?", "The 'querySelector' method is used to select the first element that matches a specified CSS selector within the document."),
    new Flashcard("What is the difference between 'slice' and 'splice' methods in JavaScript?", "'slice' returns a shallow copy of a portion of an array, while 'splice' changes the contents of an array by removing, replacing, or adding elements."),
    new Flashcard("What is the purpose of the 'JSON' object in JavaScript?", "The 'JSON' object is used to parse JSON data into JavaScript objects and stringify JavaScript objects into JSON data."),
    new Flashcard("What is the difference between 'var', 'let', and 'const' in JavaScript?", "'var' has function scope, 'let' has block scope, and 'const' also has block scope but cannot be reassigned after declaration."),
    new Flashcard("What is the purpose of the 'fetch' API in JavaScript?", "The 'fetch' API is used to make asynchronous HTTP requests and handle the response."),
    new Flashcard("What is the difference between '==', '===', and 'Object.is()' in JavaScript?", "'==' checks for loose equality with type coercion, '===' checks for strict equality without type coercion, and 'Object.is()' checks for equality with special handling for NaN and -0."),
    new Flashcard("What is the purpose of the 'async' and 'await' keywords in JavaScript?", "'async' is used to define an asynchronous function, and 'await' is used to pause the execution of an asynchronous function until a promise is fulfilled."),
    new Flashcard("What is the purpose of the 'localStorage' object in JavaScript?", "The 'localStorage' object is used to store data in the web browser with no expiration date, allowing the data to persist even after the browser is closed."),
    new Flashcard("What are arrow functions in JavaScript?", "Arrow functions are a shorter syntax for writing function expressions, with a more concise syntax and an automatically bound 'this' value."),
    new Flashcard("What is the purpose of the 'reduce' method in JavaScript?", "The 'reduce' method is used to reduce an array to a single value, by applying a function to each element of the array."),
    new Flashcard("What is the difference between 'let' and 'const' in JavaScript?", "'let' allows reassignment of values, while 'const' creates a read-only reference to a value that cannot be reassigned."),
    new Flashcard("What is the purpose of the 'setTimeout' function in JavaScript?", "The 'setTimeout' function is used to schedule the execution of a function after a specified delay."),
    new Flashcard("What is the purpose of the 'event.preventDefault()' method in JavaScript?", "The 'event.preventDefault()' method is used to prevent the default behavior of an event, such as submitting a form or following a link."),
    new Flashcard("What is the purpose of the 'try...catch' statement in JavaScript?", "The 'try...catch' statement is used to catch and handle exceptions that occur within a block of code."),
    new Flashcard("What is the difference between 'let', 'const', and 'var' in JavaScript?", "'let' and 'const' are block-scoped variables, while 'var' is function-scoped."),
    new Flashcard("What is the purpose of the 'addEventListener' method in JavaScript?", "The 'addEventListener' method is used to attach an event handler to an element, allowing it to respond to specific events."),
    new Flashcard("What is the difference between 'document.getElementById' and 'document.querySelector' in JavaScript?", "'document.getElementById' selects an element by its ID, while 'document.querySelector' selects an element using a CSS selector."),
    new Flashcard("What is the purpose of the 'Math' object in JavaScript?", "The 'Math' object provides mathematical functions and constants, allowing you to perform mathematical operations in JavaScript."),
    new Flashcard("What is the purpose of the 'typeof' operator in JavaScript?", "The 'typeof' operator is used to determine the data type of a value or variable."),
    new Flashcard("What is a callback function in JavaScript?", "A callback function is a function that is passed as an argument to another function and is invoked at a later time."),
    new Flashcard("What is the purpose of the 'Array.map' method in JavaScript?", "The 'Array.map' method creates a new array by calling a provided function on each element of the original array."),
    new Flashcard("What is the difference between 'null' and 'undefined' in JavaScript?", "'null' represents the intentional absence of any object value, while 'undefined' represents a variable that has been declared but has not been assigned a value."),
    new Flashcard("What is the purpose of the 'Array.filter' method in JavaScript?", "The 'Array.filter' method creates a new array with all elements that pass a test provided by a callback function."),
    new Flashcard("What is the difference between '==' and '===' in JavaScript?", "'==' performs type coercion and checks for equality, while '===' checks for strict equality without type coercion."),
    new Flashcard("What is the purpose of the 'Array.reduce' method in JavaScript?", "The 'Array.reduce' method applies a function against an accumulator and each element in the array, resulting in a single value."),
    new Flashcard("What are closures in JavaScript?", "Closures are functions that have access to variables from their outer (enclosing) function scope, even after the outer function has finished executing."),
    new Flashcard("What is the purpose of the 'Array.forEach' method in JavaScript?", "The 'Array.forEach' method executes a provided function once for each array element."),
    new Flashcard("What is the difference between 'let' and 'var' in JavaScript?", "'let' has block scope and is limited to the block where it is defined, while 'var' has function scope and is accessible throughout the function."),
    new Flashcard("What is the purpose of the 'Array.find' method in JavaScript?", "The 'Array.find' method returns the first element in an array that satisfies a provided testing function."),
    new Flashcard("What is the difference between synchronous and asynchronous programming in JavaScript?", "Synchronous programming executes tasks sequentially, while asynchronous programming allows tasks to be executed concurrently and non-blocking."),
    new Flashcard("What is the purpose of the 'Array.includes' method in JavaScript?", "The 'Array.includes' method checks if an array contains a specific element and returns a boolean value."),
    new Flashcard("What is the difference between 'let' and 'const' in JavaScript?", "'let' allows reassignment of values, while 'const' creates a read-only reference to a value that cannot be reassigned."),
    new Flashcard("What is the purpose of the 'Array.some' method in JavaScript?", "The 'Array.some' method tests whether at least one element in the array passes the provided testing function."),
    new Flashcard("What is the difference between 'null' and 'undefined' in JavaScript?", "'null' represents the intentional absence of any object value, while 'undefined' represents a variable that has been declared but has not been assigned a value."),
    new Flashcard("What is the purpose of the 'Array.every' method in JavaScript?", "The 'Array.every' method tests whether all elements in the array pass the provided testing function."),
    new Flashcard("What is the difference between 'let' and 'const' in JavaScript?", "'let' allows reassignment of values, while 'const' creates a read-only reference to a value that cannot be reassigned."),
    new Flashcard("What is the purpose of the 'Array.sort' method in JavaScript?", "The 'Array.sort' method sorts the elements of an array in place and returns the sorted array."),
    new Flashcard("What is the difference between 'undefined' and 'null' in JavaScript?", "'undefined' means a variable has been declared but has not been assigned a value, while 'null' is an assignment value that represents no value or an empty value."),
    new Flashcard("What is a higher-order function in JavaScript?", "A higher-order function is a function that takes one or more functions as arguments or returns a function as its result."),
    new Flashcard("What is the purpose of the 'Array.reverse' method in JavaScript?", "The 'Array.reverse' method reverses the order of the elements in an array in place."),
    new Flashcard("What is the difference between 'let' and 'var' in JavaScript?", "'let' has block scope and is limited to the block where it is defined, while 'var' has function scope and is accessible throughout the function."),
    new Flashcard("What is the purpose of the 'Array.join' method in JavaScript?", "The 'Array.join' method joins all elements of an array into a string, using a specified separator."),
    new Flashcard("What is the difference between 'let' and 'const' in JavaScript?", "'let' allows reassignment of values, while 'const' creates a read-only reference to a value that cannot be reassigned."),
    new Flashcard("What is the purpose of the 'Array.push' method in JavaScript?", "The 'Array.push' method adds one or more elements to the end of an array and returns the new length of the array."),
    new Flashcard("What is the purpose of the 'Array.pop' method in JavaScript?", "The 'Array.pop' method removes the last element from an array and returns that element."),
    new Flashcard("What is the difference between 'let' and 'const' in JavaScript?", "'let' allows reassignment of values, while 'const' creates a read-only reference to a value that cannot be reassigned."),
    new Flashcard("What is the purpose of the 'Array.unshift' method in JavaScript?", "The 'Array.unshift' method adds one or more elements to the beginning of an array and returns the new length of the array."),
    new Flashcard("What is the difference between 'undefined' and 'null' in JavaScript?", "'undefined' means a variable has been declared but has not been assigned a value, while 'null' is an assignment value that represents no value or an empty value."),
    new Flashcard("What is a higher-order function in JavaScript?", "A higher-order function is a function that takes one or more functions as arguments or returns a function as its result."),
    new Flashcard("What is the purpose of the 'Array.slice' method in JavaScript?", "The 'Array.slice' method returns a shallow copy of a portion of an array into a new array object selected from start to end."),
    new Flashcard("What is the difference between 'let' and 'var' in JavaScript?", "'let' has block scope and is limited to the block where it is defined, while 'var' has function scope and is accessible throughout the function."),
    new Flashcard("What is the purpose of the 'Array.splice' method in JavaScript?", "The 'Array.splice' method changes the contents of an array by removing, replacing, or adding elements in place, returning the removed elements."),
    new Flashcard("What is the difference between 'let' and 'const' in JavaScript?", "'let' allows reassignment of values, while 'const' creates a read-only reference to a value that cannot be reassigned."),
    new Flashcard("What is the purpose of the 'Array.concat' method in JavaScript?", "The 'Array.concat' method is used to merge two or more arrays, returning a new array."),
    // Var, Let, Const
    new Flashcard("What is the difference between var, let, and const in JavaScript?", "Var has function scope, let has block scope, and const is a constant with block scope."),
    new Flashcard("What is hoisting in JavaScript?", "Hoisting is a JavaScript mechanism where variable and function declarations are moved to the top of their containing scope."),
    new Flashcard("Can you redeclare a variable with var, let, or const in JavaScript?", "You can redeclare a variable with var, but not with let or const."),
    new Flashcard("What is the scope of a variable declared with var, let, or const?", "A variable declared with var has function scope, while let and const have block scope."),
    new Flashcard("What is the difference in behavior between var and let when declared inside a for loop?", "When declared inside a for loop, var has function scope and is shared across iterations, while let has block scope and is scoped to each iteration."),
    new Flashcard("Can you declare a constant variable with let or var in JavaScript?", "No, constant variables can only be declared with const."),
    new Flashcard("What is the difference between var and let in terms of hoisting?", "Variable declarations with var are hoisted to the top of their containing scope, while let declarations are not hoisted."),
    new Flashcard("What is the difference between var and const in terms of reassignment?", "Variables declared with var can be reassigned, while variables declared with const cannot be reassigned."),
    new Flashcard("What is the difference between let and const in terms of reassignment?", "Both let and const allow reassignment, but const variables cannot be redeclared."),
    new Flashcard("What is the difference between var and const in terms of initialization?", "Variables declared with var are automatically initialized with a value of undefined, while const variables must be initialized at the time of declaration."),

    // Closures
    new Flashcard("What is a closure in JavaScript?", "A closure is a function that has access to its own scope, the scope of the outer function, and the global scope."),
    new Flashcard("How do closures help with encapsulation in JavaScript?", "Closures allow variables and functions to be hidden and accessed only by the functions that create them, providing a form of encapsulation."),
    new Flashcard("What is the benefit of using closures in JavaScript?", "Closures allow you to create private variables and functions, implement data hiding, and create modular code."),
    new Flashcard("Can you explain the concept of lexical scope in relation to closures?", "Lexical scope refers to the ability of a function to access variables and functions that are defined outside of its own scope, but within the scope in which it is defined."),
    new Flashcard("How are closures created in JavaScript?", "Closures are created when a function is defined inside another function, and the inner function has access to the outer function's variables and parameters."),
    new Flashcard("What is the purpose of using closures in JavaScript?", "Closures are commonly used for data encapsulation, creating private variables and functions, and implementing callbacks and event handlers."),

    // Slice and Splice
    new Flashcard("What is the difference between slice and splice in JavaScript?", "Slice returns a shallow copy of a portion of an array, while splice changes the contents of an array by removing or replacing existing elements and/or adding new elements."),
    new Flashcard("How does the slice method work in JavaScript?", "The slice method returns a shallow copy of a portion of an array into a new array, without modifying the original array. It takes two parameters: start index and end index (exclusive)."),
    new Flashcard("How does the splice method work in JavaScript?", "The splice method changes the contents of an array by removing, replacing, or adding new elements. It takes three parameters: start index, number of elements to remove, and optional elements to add."),
    new Flashcard("Can the slice method be used to remove elements from an array?", "No, the slice method only returns a new array without modifying the original array. To remove elements, you can use the splice method."),
    new Flashcard("Can the splice method be used to create a shallow copy of an array?", "No, the splice method modifies the original array and does not return a new array. To create a shallow copy, you can use the slice method."),

    // Arrow Functions
    new Flashcard("What are arrow functions in JavaScript?", "Arrow functions are a concise syntax for writing function expressions in JavaScript."),
    new Flashcard("What is the syntax for defining arrow functions in JavaScript?", "Arrow functions have a shorter syntax compared to regular function expressions. The basic syntax is: (parameters) => { function body }"),
    new Flashcard("What is the difference between arrow functions and regular functions in terms of 'this' binding?", "Arrow functions do not have their own 'this' value; they inherit the 'this' value from the surrounding context."),
    new Flashcard("Can arrow functions be used as constructors?", "No, arrow functions cannot be used as constructors because they do not have their own 'this' value."),
    new Flashcard("What is the benefit of using arrow functions in JavaScript?", "Arrow functions have a more concise syntax, lexically bind 'this' from the surrounding context, and do not create their own 'this' value."),
    // Add more flashcards related to JavaScript topics here...
];

export const reactFlashcardsData = [
    new Flashcard("What is React?", "React is a JavaScript library for building user interfaces."),
    new Flashcard("What is JSX?", "JSX is a syntax extension for JavaScript that allows you to write HTML-like code within JavaScript."),
    new Flashcard("What is a component in React?", "A component in React is a reusable piece of UI that can be composed together to build complex UIs."),
    new Flashcard("What is the difference between functional and class components?", "Functional components are simple JavaScript functions that accept props as arguments and return JSX. Class components are ES6 classes that extend the React.Component class and have a render method."),
    new Flashcard("What is the virtual DOM in React?", "The virtual DOM is a lightweight copy of the actual DOM that React uses to perform efficient updates and minimize direct manipulation of the actual DOM."),
    new Flashcard("What is the purpose of state in React?", "State is a JavaScript object that holds data specific to a component. It allows components to keep track of changing data and update the UI based on that data."),
    new Flashcard("What is the difference between props and state?", "Props are read-only data passed from parent components to child components, while state is mutable data managed within a component."),
    new Flashcard("What are React hooks?", "React hooks are functions that allow you to use state and other React features in functional components without writing a class."),
    new Flashcard("What is the purpose of the useEffect hook?", "The useEffect hook is used to perform side effects in functional components, such as fetching data, subscribing to events, or manually changing the DOM."),
    new Flashcard("What is the purpose of the useState hook?", "The useState hook is used to add state to functional components. It returns a state variable and a function to update that variable."),
    new Flashcard("What is the purpose of the useContext hook?", "The useContext hook is used to access the value of a React context in functional components."),
    new Flashcard("What is the purpose of the useRef hook?", "The useRef hook is used to create a mutable reference that persists across component renders."),
    new Flashcard("What is the purpose of the useMemo hook?", "The useMemo hook is used to memoize expensive calculations and avoid unnecessary re-computations."),
    new Flashcard("What is the purpose of the useCallback hook?", "The useCallback hook is used to memoize callback functions and prevent unnecessary re-renders in child components."),
    new Flashcard("What is the purpose of the useReducer hook?", "The useReducer hook is used to manage complex state logic by specifying how state should be updated based on a given action."),
    new Flashcard("What is the purpose of the useHistory hook?", "The useHistory hook is used to access and manipulate the browser history in React Router."),
    new Flashcard("What is the purpose of the useParams hook?", "The useParams hook is used to access the dynamic parameters of a route in React Router."),
    new Flashcard("What is the purpose of the useLocation hook?", "The useLocation hook is used to access the current URL location in React Router."),
    new Flashcard("What is the purpose of the withRouter higher-order component?", "The withRouter higher-order component is used to access the history, match, and location props in a component that is not directly rendered by a Route component."),
    new Flashcard("What is a React fragment?", "A React fragment is a way to group multiple elements without adding an extra node to the DOM."),
    new Flashcard("What is the purpose of the key prop in React?", "The key prop is used to uniquely identify elements in a list and optimize the rendering process."),
    new Flashcard("What is conditional rendering in React?", "Conditional rendering is the process of displaying different UI components or content based on certain conditions."),
    new Flashcard("What is the purpose of prop drilling in React?", "Prop drilling is the process of passing props through multiple levels of nested components, even if some intermediate components do not need the props."),
    new Flashcard("What is the context API in React?", "The context API is a way to share data between components without passing props manually through every intermediate component."),
    new Flashcard("What is the purpose of React Router?", "React Router is a library that allows for declarative routing in a React application, enabling navigation between different views or pages."),
    new Flashcard("What is the difference between BrowserRouter and HashRouter in React Router?", "BrowserRouter uses the HTML5 history API for cleaner URLs, while HashRouter uses the URL hash to manage routing."),
    new Flashcard("What is Redux?", "Redux is a predictable state container for JavaScript apps, commonly used with React to manage application state in a centralized manner."),
    new Flashcard("What is component lifecycle in React?", "Component lifecycle refers to the series of phases a component goes through, from initialization to destruction."),
    new Flashcard("What is React Router?", "React Router is a popular library for handling routing in React applications."),
    new Flashcard("What are props in React?", "Props (short for properties) are a way to pass data from a parent component to a child component in React."),
    new Flashcard("What is state in React?", "State is an object that holds data specific to a component and can be updated over time."),
    new Flashcard("What is the purpose of the 'setState' method in React?", "The 'setState' method is used to update the state of a component and trigger a re-render."),
    new Flashcard("What is conditional rendering in React?", "Conditional rendering is a way to show different components or content based on certain conditions."),
    new Flashcard("What is the purpose of the 'key' prop in React?", "The 'key' prop is used to uniquely identify elements in a list and optimize rendering performance."),
    new Flashcard("What is React Context?", "React Context is a feature that allows you to share data between components without passing props manually through each level of the component tree."),
    new Flashcard("What is the purpose of the 'useContext' hook in React?", "The 'useContext' hook allows you to consume values from React Context in functional components."),
    new Flashcard("What is React Redux?", "React Redux is a library that provides a predictable state container for managing the state of your React application."),
    new Flashcard("What are React components lifecycle methods?", "React components have lifecycle methods that allow you to perform actions at different stages of a component's existence, such as mounting, updating, and unmounting."),
    new Flashcard("What is the purpose of the 'useRef' hook in React?", "The 'useRef' hook allows you to create a mutable reference that persists across component renders."),
    new Flashcard("What is React Native?", "React Native is a framework for building native mobile apps using React."),
    new Flashcard("What is the purpose of the 'useEffect' hook in React Native?", "The 'useEffect' hook in React Native allows you to perform side effects, such as fetching data or subscribing to events, in functional components."),
    new Flashcard("What is the difference between React and React Native?", "React is a library for building user interfaces for web applications, while React Native is a framework for building native mobile apps."),
    new Flashcard("What is the purpose of the 'StyleSheet' component in React Native?", "The 'StyleSheet' component in React Native is used to define and manage styles for components."),
    new Flashcard("What is the purpose of the 'TouchableOpacity' component in React Native?", "The 'TouchableOpacity' component in React Native provides a touchable area that can be used to handle user interactions."),
    new Flashcard("What is the purpose of the 'FlatList' component in React Native?", "The 'FlatList' component in React Native is used to efficiently render large lists of data."),
    new Flashcard("What is the purpose of the 'AsyncStorage' API in React Native?", "The 'AsyncStorage' API in React Native allows you to persist data asynchronously on the device."),
    new Flashcard("What is the purpose of the 'TextInput' component in React Native?", "The 'TextInput' component in React Native provides a way for users to enter text input."),
    new Flashcard("What is the purpose of the 'ActivityIndicator' component in React Native?", "The 'ActivityIndicator' component in React Native is used to show a loading spinner."),
    new Flashcard("What is the purpose of the 'Image' component in React Native?", "The 'Image' component in React Native is used to display images in the app."),
    new Flashcard("What is React Router?", "React Router is a library that enables routing and navigation in React applications, allowing for multiple pages or views within a single-page application."),
    new Flashcard("What is React Hooks?", "React Hooks are functions that allow you to use state and other React features in functional components, eliminating the need for class components in many cases."),
    new Flashcard("What is the purpose of the 'useEffect' hook in React?", "The 'useEffect' hook in React allows you to perform side effects, such as fetching data or subscribing to events, in functional components."),
    new Flashcard("What is the virtual DOM in React?", "The virtual DOM is a lightweight copy of the actual DOM that React uses to optimize rendering and efficiently update only the necessary parts of the user interface."),
    new Flashcard("What is the purpose of the 'useState' hook in React?", "The 'useState' hook allows you to add state to functional components, enabling them to manage and update their own data."),
    new Flashcard("What is JSX in React?", "JSX is a syntax extension for JavaScript that allows you to write HTML-like code in your JavaScript files, making it easier to create and manipulate React elements."),
    new Flashcard("What is the purpose of the 'props' object in React?", "The 'props' object allows you to pass data from a parent component to a child component, making it possible to customize and reuse components."),
    new Flashcard("What is React Context?", "React Context provides a way to share data between components without passing props manually through each level of the component tree."),
    new Flashcard("What is the purpose of the 'useContext' hook in React?", "The 'useContext' hook allows you to consume values from React Context in functional components."),
    new Flashcard("What is the purpose of the 'key' prop in React?", "The 'key' prop is used to uniquely identify elements in a list, helping React optimize rendering and efficiently update the list."),
    new Flashcard("What is Redux in React?", "Redux is a predictable state management library for JavaScript applications, commonly used with React to manage global state."),
    new Flashcard("What is an action in Redux?", "An action is a plain JavaScript object that describes an event or change in the application, typically triggered by user interaction."),
    new Flashcard("What is a reducer in Redux?", "A reducer is a pure function that takes the current state and an action, and returns a new state based on the action's type and payload."),
    new Flashcard("What is the purpose of the 'connect' function in React Redux?", "The 'connect' function is used to connect a React component to the Redux store, allowing it to access state and dispatch actions."),
    new Flashcard("What is a middleware in Redux?", "A middleware in Redux is a function that sits between the dispatching of an action and the processing of that action by the reducer, allowing for additional functionality or side effects."),
    new Flashcard("What is the purpose of the 'Provider' component in React Redux?", "The 'Provider' component is used to wrap the root component of a React application, providing access to the Redux store for all components in the component tree."),
    new Flashcard("What is the difference between 'mapStateToProps' and 'mapDispatchToProps' in React Redux?", "'mapStateToProps' is used to map the state from the Redux store to the props of a component, while 'mapDispatchToProps' is used to map dispatch actions to the props of a component."),
    new Flashcard("What is the purpose of the 'thunk' middleware in Redux?", "The 'thunk' middleware in Redux allows for writing action creators that return functions instead of plain objects, enabling asynchronous actions."),
    new Flashcard("What is the purpose of the 'reselect' library in Redux?", "The 'reselect' library provides a way to efficiently compute derived data from the Redux state, reducing unnecessary re-computations."),
    new Flashcard("What is the purpose of the 'immutable' library in Redux?", "The 'immutable' library provides immutable data structures that can be used with Redux, ensuring immutability and efficient updates."),
    new Flashcard("What are React Hooks?", "React Hooks are functions that allow you to use state and other React features in functional components, eliminating the need for class components in many cases."),
    new Flashcard("What is the purpose of the 'useState' hook in React?", "The 'useState' hook allows you to add state to functional components, enabling them to manage and update their own data."),
    new Flashcard("What is the purpose of the 'useEffect' hook in React?", "The 'useEffect' hook in React allows you to perform side effects, such as fetching data or subscribing to events, in functional components."),
    new Flashcard("What is the difference between 'useState' and 'useReducer' in React?", "'useState' is a hook that manages a single state value, while 'useReducer' is a hook that manages more complex state transitions with a reducer function."),
    new Flashcard("What is the purpose of the 'useContext' hook in React?", "The 'useContext' hook allows you to consume values from React Context in functional components."),
    new Flashcard("What is the purpose of the 'useRef' hook in React?", "The 'useRef' hook allows you to create a mutable reference that persists across component renders."),
    new Flashcard("What is the purpose of the 'useCallback' hook in React?", "The 'useCallback' hook is used to memoize functions, preventing unnecessary re-renders of child components."),
    new Flashcard("What is the purpose of the 'useMemo' hook in React?", "The 'useMemo' hook is used to memoize values, preventing unnecessary re-computations."),
    new Flashcard("What is the purpose of the 'useLayoutEffect' hook in React?", "The 'useLayoutEffect' hook is similar to 'useEffect', but it fires synchronously after all DOM mutations, allowing you to perform measurements or DOM manipulations."),
    new Flashcard("What is the purpose of the 'useReducer' hook in React?", "The 'useReducer' hook is used to manage more complex state transitions with a reducer function, similar to how 'redux' works."),
    new Flashcard("What is React Testing Library?", "React Testing Library is a testing utility for React applications that focuses on testing user interactions and ensuring the application behaves as expected from the user's perspective."),
    new Flashcard("What is Jest?", "Jest is a JavaScript testing framework that is commonly used for testing React applications. It provides a simple and intuitive API for writing tests and comes with built-in features like mocking and assertion libraries."),
    new Flashcard("What is the purpose of 'render' function in React Testing Library?", "The 'render' function in React Testing Library is used to render a React component into a virtual DOM, allowing you to interact with it and make assertions about its behavior."),
    new Flashcard("What is the purpose of 'fireEvent' function in React Testing Library?", "The 'fireEvent' function in React Testing Library is used to simulate user interactions, such as clicking buttons or typing into input fields, in order to test the behavior of the component."),
    new Flashcard("What is the purpose of 'screen' object in React Testing Library?", "The 'screen' object in React Testing Library provides utilities to query and interact with elements rendered by the component, allowing you to make assertions about the rendered output."),
    new Flashcard("What is the purpose of 'waitFor' function in React Testing Library?", "The 'waitFor' function in React Testing Library is used to wait for asynchronous operations, such as data fetching or state updates, to complete before making assertions about the component's behavior."),
    new Flashcard("What is the purpose of 'act' function in React Testing Library?", "The 'act' function in React Testing Library is used to wrap code that has side effects or updates state, ensuring that all updates are processed before making assertions."),
    new Flashcard("What is snapshot testing in React?", "Snapshot testing is a testing technique in React where a snapshot of the component's rendered output is saved."),
    new Flashcard("What is React Native?", "React Native is a framework for building mobile applications using React and JavaScript, allowing you to write code once and deploy it on both iOS and Android platforms."),
    new Flashcard("What are some advantages of using React Native?", "Some advantages of using React Native include code reusability, faster development cycles, and a native-like user experience."),
    new Flashcard("What is the purpose of the 'StyleSheet' component in React Native?", "The 'StyleSheet' component in React Native is used to define styles for components using a JavaScript object syntax similar to CSS."),
    new Flashcard("What is the difference between React and React Native?", "React is a JavaScript library for building user interfaces on the web, while React Native is a framework for building mobile applications using React."),
    new Flashcard("What are some core components in React Native?", "Some core components in React Native include 'View', 'Text', 'Image', and 'ScrollView', among others."),
    new Flashcard("What is the purpose of the 'Flexbox' layout in React Native?", "The 'Flexbox' layout in React Native provides a flexible way to arrange and align components within a container."),
    new Flashcard("What is the 'Touchable' component in React Native?", "The 'Touchable' component in React Native provides touch-based interactions, such as tapping, swiping, and long-pressing, for components."),
    new Flashcard("What is the purpose of the 'AsyncStorage' API in React Native?", "The 'AsyncStorage' API in React Native provides a simple way to persist data on the device asynchronously."),
    new Flashcard("What is the purpose of the 'FlatList' component in React Native?", "The 'FlatList' component in React Native is used to efficiently render large lists of data, providing performance optimizations such as lazy loading and recycling of components."),
    new Flashcard("What is the purpose of the 'Navigator' component in React Native?", "The 'Navigator' component in React Native is used for navigation between screens or views within a mobile application."),
    new Flashcard("What is JSX in React?", "JSX is a syntax extension for JavaScript that allows you to write HTML-like code in your JavaScript files, making it easier to describe the structure and appearance of your React components."),
    new Flashcard("What is the virtual DOM in React?", "The virtual DOM is a lightweight copy of the actual DOM, maintained by React, which allows for efficient updates and rendering of components."),
    new Flashcard("What is the purpose of the 'key' prop in React?", "The 'key' prop is used to uniquely identify elements in a list, helping React efficiently update and render components."),
    new Flashcard("What is conditional rendering in React?", "Conditional rendering in React is the practice of rendering different content or components based on certain conditions or state values."),
    new Flashcard("What are React Fragments?", "React Fragments are a way to group multiple elements together without adding an extra DOM node, allowing for cleaner code and improved performance."),
    new Flashcard("What is prop drilling in React?", "Prop drilling in React is the process of passing props from one component to another through intermediate components, even if those intermediate components don't need the props."),
    new Flashcard("What is the purpose of the 'context' API in React?", "The 'context' API in React allows you to pass data down the component tree without explicitly passing props at each level, making it easier to share data between components."),
    new Flashcard("What are React portals?", "React portals allow you to render a component's content in a different part of the DOM tree, outside of its parent component, enabling more flexible rendering and modals."),
    new Flashcard("What is the purpose of the 'ErrorBoundary' component in React?", "The 'ErrorBoundary' component in React is used to catch and handle errors that occur during rendering or in lifecycle methods of its child components."),
    new Flashcard("What is the purpose of the 'PureComponent' in React?", "The 'PureComponent' in React is a base class that provides a performance optimization by automatically implementing a shallow comparison of props and state to prevent unnecessary re-renders."),
];

export const angularFlashcardsData = [
    new Flashcard("What is Angular?", "Angular is a popular JavaScript framework for building web applications."),
    new Flashcard("What are the key features of Angular?", "Some key features of Angular include two-way data binding, dependency injection, and modular architecture."),
    new Flashcard("What is a component in Angular?", "A component is a building block of an Angular application that contains the template, data, and behavior."),
    new Flashcard("What is Angular CLI?", "Angular CLI is a command-line interface tool that helps in creating, building, and testing Angular applications."),
    new Flashcard("What is Angular routing?", "Angular routing is a mechanism that allows navigating between different views or pages in a single-page application."),
    new Flashcard("What is Angular template syntax?", "Angular template syntax is a combination of HTML and Angular-specific elements and attributes used to define the structure and behavior of a component's template."),
    new Flashcard("What is Angular module?", "An Angular module is a container for organizing components, directives, pipes, and services."),
    new Flashcard("What is Angular service?", "An Angular service is a reusable code that can be injected into components to provide a specific functionality."),
    new Flashcard("What is Angular directive?", "An Angular directive is a way to extend HTML with custom behavior or functionality."),
    new Flashcard("What is Angular binding?", "Angular binding is a way to connect the data in the component class with the HTML template."),
    new Flashcard("What is Angular CLI?", "Angular CLI is a command-line interface tool that helps in creating, building, and testing Angular applications."),
    new Flashcard("What is Angular Material?", "Angular Material is a UI component library for Angular applications that provides pre-built, customizable UI components."),
    new Flashcard("What is Angular Ivy?", "Angular Ivy is the next-generation rendering engine of Angular that improves performance, bundle size, and developer experience."),
    new Flashcard("What is Angular Reactive Forms?", "Angular Reactive Forms is an approach to creating and managing complex forms in Angular using reactive programming techniques."),
    new Flashcard("What is Angular HTTP Client?", "Angular HTTP Client is a module that allows making HTTP requests to a server and handling responses in Angular applications."),
    new Flashcard("What is Angular testing?", "Angular testing is the process of writing and running tests to ensure that Angular applications are working correctly and as expected."),
    new Flashcard("What is Angular change detection?", "Angular change detection is a mechanism that automatically updates the view when the underlying data changes."),
    new Flashcard("What is Angular dependency injection?", "Angular dependency injection is a design pattern used to manage the dependencies of components and services in an Angular application."),
    new Flashcard("What is Angular pipes?", "Angular pipes are a feature that allows transforming and formatting data in the template."),
    new Flashcard("What is Angular Directives?", "Angular directives are instructions in the DOM that tell Angular how to modify or manipulate the DOM elements."),
    new Flashcard("What are Angular decorators?", "Angular decorators are special types of functions that can be used to modify or enhance the behavior of classes, methods, or properties in Angular."),
    new Flashcard("What is Angular lazy loading?", "Angular lazy loading is a technique that allows loading modules or components on-demand, improving the initial loading time of an application."),
    new Flashcard("What is Angular animation?", "Angular animation is a powerful tool for creating visual effects and animations in Angular applications."),
    new Flashcard("What is Angular SSR?", "Angular SSR (Server-Side Rendering) is a technique that allows rendering Angular applications on the server, improving performance and SEO."),
    new Flashcard("What is Angular lifecycle hooks?", "Angular lifecycle hooks are methods that are called at specific stages of a component's lifecycle, allowing developers to perform custom logic."),
    new Flashcard("What is Angular forms?", "Angular forms are a way to handle user input and validation in Angular applications."),
    new Flashcard("What is Angular router outlet?", "Angular router outlet is a directive that acts as a placeholder where the router renders the views based on the current URL."),
    new Flashcard("What is Angular directives ngIf and ngFor?", "Angular directives ngIf and ngFor are used for conditionally rendering elements and iterating over arrays or collections in the template."),
    new Flashcard("What is Angular ngModule?", "Angular NgModule is a decorator that is used to define and configure various aspects of an Angular module."),
    new Flashcard("What is Angular zone?", "Angular zone is a concept that allows Angular to track and manage asynchronous operations, such as event handling and HTTP requests."),
    new Flashcard("What is Angular HttpClient Interceptor?", "Angular HttpClient Interceptor is a feature that allows intercepting and modifying HTTP requests and responses in Angular applications."),
    new Flashcard("What is Angular ng-template?", "Angular ng-template is a directive that allows defining reusable templates in Angular applications."),
    new Flashcard("What is Angular ng-content?", "Angular ng-content is a directive that allows passing content into a component from its parent component."),
    new Flashcard("What is Angular ngZone?", "Angular ngZone is a service that provides a way to execute code outside of Angular's change detection zone."),
    new Flashcard("What is Angular ngModel?", "Angular ngModel is a directive that provides two-way data binding between a form control element and a component."),
    new Flashcard("What is Angular router guards?", "Angular router guards are used to control access to certain routes in an Angular application based on certain conditions."),
    new Flashcard("What is Angular dependency injection hierarchy?", "Angular dependency injection hierarchy is a mechanism that determines how dependencies are resolved when multiple providers are available."),
    new Flashcard("What is Angular ngClass?", "Angular ngClass is a directive that allows dynamically adding or removing CSS classes based on certain conditions."),
    new Flashcard("What is Angular ngStyle?", "Angular ngStyle is a directive that allows dynamically applying inline styles to HTML elements based on certain conditions."),
    new Flashcard("What is Angular ngZone?", "Angular ngZone is a service that provides a way to execute code outside of Angular's change detection zone."),
    new Flashcard("What is Angular ng-template?", "Angular ng-template is a directive that allows defining reusable templates in Angular applications."),
    new Flashcard("What is Angular ng-content?", "Angular ng-content is a directive that allows passing content into a component from its parent component."),
    new Flashcard("What is Angular ngZone?", "Angular ngZone is a service that provides a way to execute code outside of Angular's change detection zone."),
    new Flashcard("What is Angular ngModel?", "Angular ngModel is a directive that provides two-way data binding between a form control element and a component."),
    new Flashcard("What is Angular router guards?", "Angular router guards are used to control access to certain routes in an Angular application based on certain conditions."),
    new Flashcard("What is Angular dependency injection hierarchy?", "Angular dependency injection hierarchy is a mechanism that determines how dependencies are resolved when multiple providers are available."),
    new Flashcard("What is Angular ngClass?", "Angular ngClass is a directive that allows dynamically adding or removing CSS classes based on certain conditions."),
    new Flashcard("What is Angular ngStyle?", "Angular ngStyle is a directive that allows dynamically applying inline styles to HTML elements based on certain conditions."),
    new Flashcard("What is Angular reactive forms?", "Angular reactive forms is an approach to handling form inputs and validation using reactive programming techniques."),
    new Flashcard("What is Angular template-driven forms?", "Angular template-driven forms is an approach to handling form inputs and validation using HTML-based templates."),
    new Flashcard("What is Angular component interaction?", "Angular component interaction refers to the communication between components in an Angular application."),
    new Flashcard("What are Angular services?", "Angular services are singleton objects that are used to share data and functionality across multiple components."),
    new Flashcard("What is Angular dependency injection (DI)?", "Angular dependency injection is a design pattern used to manage the dependencies of components and services in an Angular application."),
    new Flashcard("What is Angular module?", "An Angular module is a container for organizing and packaging related components, services, directives, and other code."),
    new Flashcard("What is Angular data binding?", "Angular data binding is the automatic synchronization of data between the model and the view."),
    new Flashcard("What are Angular directives?", "Angular directives are instructions in the DOM that tell Angular how to modify or manipulate the DOM elements."),
    new Flashcard("What is Angular CLI?", "Angular CLI is a command-line interface tool that helps in creating, building, and testing Angular applications."),
    new Flashcard("What is Angular routing?", "Angular routing is a mechanism that allows navigating between different views or pages in an Angular application."),
    new Flashcard("What is Angular template syntax?", "Angular template syntax is a set of rules and conventions for writing HTML templates with additional Angular-specific features."),
    new Flashcard("What is Angular change detection?", "Angular change detection is a mechanism that automatically updates the view when the underlying data changes."),
    new Flashcard("What is Angular testing?", "Angular testing is the process of verifying the correctness and functionality of Angular applications."),
    new Flashcard("What is Angular CLI?", "Angular CLI (Command Line Interface) is a powerful tool that helps in creating, scaffolding, building, and testing Angular applications."),
    new Flashcard("What is Angular Material?", "Angular Material is a UI component library for Angular applications that provides pre-built components following the Material Design guidelines."),
    new Flashcard("What is Angular Ivy?", "Angular Ivy is the next-generation compilation and rendering pipeline for Angular applications, bringing improved performance and smaller bundle sizes."),
    new Flashcard("What is Angular zone.js?", "Angular zone.js is a library that helps Angular applications to track and manage asynchronous operations and change detection."),
    new Flashcard("What is Angular interceptors?", "Angular interceptors are a feature that allows intercepting and modifying HTTP requests and responses in Angular applications."),
    new Flashcard("What is Angular decorators?", "Angular decorators are special types of functions that can be used to modify or enhance the behavior of classes, methods, or properties in Angular."),
    new Flashcard("What is Angular lazy loading?", "Angular lazy loading is a technique that allows loading modules or components on-demand, improving the initial loading time of an application."),
    new Flashcard("What is Angular animation?", "Angular animation is a powerful tool for creating visual effects and animations in Angular applications."),
    new Flashcard("What is Angular SSR?", "Angular SSR (Server-Side Rendering) is a technique that allows rendering Angular applications on the server, improving performance and SEO."),
    new Flashcard("What is Angular ng-template?", "Angular ng-template is a directive that allows defining reusable templates in Angular applications."),
    new Flashcard("What is Angular ng-content?", "Angular ng-content is a directive that allows passing content into a component from its parent component."),
    new Flashcard("What is Angular ngZone?", "Angular ngZone is a service that provides a way to execute code outside of Angular's change detection zone."),
    new Flashcard("What is Angular ngModel?", "Angular ngModel is a directive that provides two-way data binding between a form control element and a component."),
    new Flashcard("What is Angular router guards?", "Angular router guards are used to control access to certain routes in an Angular application based on certain conditions."),
    new Flashcard("What is Angular dependency injection hierarchy?", "Angular dependency injection hierarchy is a mechanism that determines how dependencies are resolved when multiple providers are available."),
    new Flashcard("What is Angular ngClass?", "Angular ngClass is a directive that allows dynamically adding or removing CSS classes based on certain conditions."),
    new Flashcard("What is Angular ngStyle?", "Angular ngStyle is a directive that allows dynamically applying inline styles to HTML elements based on certain conditions."),
    new Flashcard("What is Angular reactive forms?", "Angular reactive forms is an approach to handling form inputs and validation using reactive programming techniques."),
    new Flashcard("What is Angular template-driven forms?", "Angular template-driven forms is an approach to handling form inputs and validation using HTML-based templates."),
    new Flashcard("What is Angular component interaction?", "Angular component interaction refers to the communication between components in an Angular application."),
    new Flashcard("What are Angular services?", "Angular services are singleton objects that are used to share data and functionality across multiple components."),
    new Flashcard("What is Angular dependency injection (DI)?", "Angular dependency injection is a design pattern used to manage the dependencies of components and services in an Angular application."),
    new Flashcard("What is Angular module?", "An Angular module is a container for organizing and packaging related components, services, directives, and other code."),
    new Flashcard("What is Angular data binding?", "Angular data binding is the automatic synchronization of data between the model and the view."),
    new Flashcard("What are Angular directives?", "Angular directives are instructions in the DOM that tell Angular how to modify or manipulate the DOM elements."),
    new Flashcard("What is Angular CLI?", "Angular CLI is a command-line interface tool that helps in creating, building, and testing Angular applications."),
    new Flashcard("What is Angular routing?", "Angular routing is a mechanism that allows navigating between different views or pages in an Angular application."),
    new Flashcard("What is Angular template syntax?", "Angular template syntax is a set of rules and conventions for writing HTML templates with additional Angular-specific features."),
    new Flashcard("What is Angular change detection?", "Angular change detection is a mechanism that automatically updates the view when the underlying data changes."),
    new Flashcard("What is Angular testing?", "Angular testing is the process of verifying the correctness and functionality of Angular applications."),
    new Flashcard("What is Angular CLI?", "Angular CLI (Command Line Interface) is a powerful tool that helps in creating, scaffolding, building, and testing Angular applications."),
    new Flashcard("What is Angular Material?", "Angular Material is a UI component library for Angular applications that provides pre-built components following the Material Design guidelines."),
    new Flashcard("What is Angular Ivy?", "Angular Ivy is the next-generation compilation and rendering pipeline for Angular applications, bringing improved performance and smaller bundle sizes."),
    new Flashcard("What is Angular zone.js?", "Angular zone.js is a library that helps Angular applications to track and manage asynchronous operations and change detection."),
    new Flashcard("What is Angular interceptors?", "Angular interceptors are a feature that allows intercepting and modifying HTTP requests and responses in Angular applications."),
    new Flashcard("What is Angular decorators?", "Angular decorators are special types of functions that can be used to modify or enhance the behavior of classes, methods, or properties in Angular."),
    new Flashcard("What is Angular lazy loading?", "Angular lazy loading is a technique that allows loading modules or components on-demand, improving the initial loading time of an application."),
    new Flashcard("What is Angular animation?", "Angular animation is a powerful tool for creating visual effects and animations in Angular applications."),
    new Flashcard("What is Angular SSR?", "Angular SSR (Server-Side Rendering) is a technique that allows rendering Angular applications on the server, improving performance and SEO."),
];